In [17]:
import numpy as np
import matplotlib.pyplot as plt

In [18]:
Δx = 2
Δt = 0.1
k = 0.835
λ = k * Δt/Δx**2
u = np.array([0,0,0,0])
contorno = np.array([100,50])
matriz_coeficiente = np.array(
    [[2*(1+λ),-λ,0,0],
     [-λ,2*(1+λ),-λ,0],
     [0, -λ,2*(1+λ),-λ],
     [0,0,-λ,2*(1+λ)]]
     )

matriz_ampliada = np.array(
    [
    λ*u[1] + 2*λ*contorno[0] + (1-λ)*u[0],
    λ*u[2] + 2*(1-λ)*u[1] + λ*u[0],
    λ*u[3] + 2*(1-λ)*u[2] + λ*u[1],
    λ*u[2] + 2*λ*contorno[1] + (1-λ)*u[3]]).T

In [19]:
t = 0.2
for _ in np.arange(0,t,Δt):
    u = np.linalg.solve(matriz_coeficiente,matriz_ampliada)
    matriz_ampliada = np.array(
    [
    λ*u[1] + 2*λ*contorno[0] + 2*(1-λ)*u[0],
    λ*u[2] + 2*(1-λ)*u[1] + λ*u[0],
    λ*u[3] + 2*(1-λ)*u[2] + λ*u[1],
    λ*u[2] + 2*λ*contorno[1] + 2*(1-λ)*u[3]]).T

A matriz ampliada em 0.2 é
[8.18011753 0.08407044 0.04267667 4.09006532]
A matriz ampliada em 0.2 é
[12.02395821  0.24624183  0.12625023  6.01202395]


In [20]:
u

array([4.00726894, 0.08257807, 0.04223172, 2.00364732])