In [33]:
import numpy as np
import matplotlib.pyplot as plt
from functions import *

In [34]:
num_pontos = 4
L = 10 # comprimento da barra
Δx = 2 #L / num_pontos
Δt = 0.1
k = 0.835
λ = k * Δt/Δx**2
condição_inicial = 0.
contorno = np.array([100.,50.])
variavel = np.ones(num_pontos) * condição_inicial
matriz_coeficiente = CrankNicolson.gerarMatrizCoeficientes(num_pontos,λ)
matriz_ampliada = CrankNicolson.gerarMatrizAmpliada(num_pontos,contorno,variavel,λ)

In [35]:
matriz_coeficiente

array([[ 2.04175 , -0.020875,  0.      ,  0.      ],
       [-0.020875,  2.04175 , -0.020875,  0.      ],
       [ 0.      , -0.020875,  2.04175 , -0.020875],
       [ 0.      ,  0.      , -0.020875,  2.04175 ]])

In [36]:
matriz_ampliada

array([[4.175 ],
       [0.    ],
       [0.    ],
       [2.0875]])

In [37]:
for _ in np.arange(0,0.2,Δt):
    variavel = np.linalg.solve(matriz_coeficiente,matriz_ampliada)
    matriz_ampliada = CrankNicolson.gerarMatrizAmpliada(num_pontos,contorno,variavel,λ)

In [38]:
variavel

array([[4.00726894],
       [0.08257807],
       [0.04223172],
       [2.00364732]])